# Generated by Django 6.0.5 on 2026-05-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_featureflag_tenant_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
